### ISSUE TITLE
Colorscheme applied inconsistently

### ISSUE THREAD

**Issue by flaamjab** [srcery-colors/srcery-vim#122]
Hello.

I've been recently configuring syntax highlighting and noticed there are some inconsistencies depending on when the colorscheme is set. It seems to happen only with srcery specifically.

In Vim 8.2.2121 with the most basic config:
```viml
set number
set tabstop=4
set shiftwidth=4
set expandtab
set nowrap

packadd! srcery-vim
colorscheme srcery
```

I get the following highlights in a C file:
![2024-06-06T12:06:45](https://github.com/srcery-colors/srcery-vim/assets/46999161/e30c32a9-fbad-4581-876b-8b0617e32600)

If I call `colorscheme srcery` in the editor AFTER opening the C file the highlights change.
![2024-06-06T12:06:07](https://github.com/srcery-colors/srcery-vim/assets/46999161/3c61c7ac-fc22-4601-a7b9-e6d87255232c)

I get the same behavior in Neovim 0.10 with only srcery-vim installed.

Some other filetypes are affected, netrw, for instance.

**Comment by flaamjab** [comment]
Now that I think about it, this behavior seems reasonable as there are some filetype-specific highlights set in the after directory. That's definitely unexpected though.

**Comment by roosta** [comment]
Hi, thanks for reporting. I think the issue is in this [file](https://github.com/srcery-colors/srcery-vim/blob/master/after/syntax/vim.vim), if I move those highlights to [srcery.vim](https://github.com/srcery-colors/srcery-vim/blob/master/colors/srcery.vim) the issue is gone, seems those particular highlights can't be `after` it seems

**Comment by roosta** [comment]
hmm, got distracted by that particular file type because I was testing in my `vimrc`, which exhibited inconsistent color changes when I sourced it. 

Like you said, this is probably related to the plugin folder structure after the refactor and how the syntax colors are loaded. Not sure it's something that can be addressed.

**Comment by flaamjab** [comment]
Alright then, I guess it's not much of an issue anyway.

**Comment by MindTooth** [comment]
> Hi, thanks for reporting. I think the issue is in this [file](https://github.com/srcery-colors/srcery-vim/blob/master/after/syntax/vim.vim), if I move those highlights to [srcery.vim](https://github.com/srcery-colors/srcery-vim/blob/master/colors/srcery.vim) the issue is gone, seems those particular highlights can't be `after` it seems

Is this some logic we should review again?  The original pull request that added this was referring to [dracula](https://github.com/dracula/vim), but I can't see that they use that logic anymore. 🤔 


Seems I commented a bit, but can't remember anything from it. 🤣

**Comment by roosta** [comment]
Seems dracula has moved away from that file structure https://github.com/dracula/vim/pull/321
I think we should do the same. If it cause inconsistent colors and other issues it's not worth the few miliseconds of startup time we save.

I can look at it in a bit, got some time off next month, I'll try and publish a PR to fix it.

**Comment by roosta** [comment]
ref: https://github.com/dracula/vim/issues/280
