### ISSUE TITLE
[Color choice] Orange color looks out of place

### ISSUE THREAD

**Issue by McSinyx** [srcery-colors/srcery-vim#41]
The current orange color doesn't seem to fit the overall vivid style. I suggest to change from [xterm color 166 to 202](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg) as followed (the upper line uses the new 202):

![202-166](https://user-images.githubusercontent.com/13689192/58366173-a236cb80-7ef8-11e9-902a-485636784a55.png)

I also notice that green and blue doesn't have the relative luminance (seems to be darker than other ones).

**Comment by roosta** [comment]
I agree with the orange, 202 seems like a better fit, a bit more vibrant. As for the green and blue, I see your point but there are many factors to consider. I tried to balance earthy and vibrant if that makes any sense, if I increase its saturation or lightness the color loses its earthy tone in my opinion.

Another factor is just how it looks contrasted against the background and its light counterpart, and against the rest of the colors, and how distinct it is. Another consideration I had when picking the colors is how well light text works with a dark color background, and vice versa, albeit that it could be argued that this would be even better if the colors were a bit more vibrant.

Sometimes when just looking at just the palette from a pure color perspective doesn't give the full impression as to how it feels in the editor, and how text looks when the color is applied, how easy is it on the eyes. 

Colors are really subjective, and I **totally** see where you're coming from but at this time I'd need a really good reason to change them, they've been propagated *everywhere* and changing them now is a rather large undertaking. 

That said it's interesting that you point out those two particular colors, because they've been a point of contention for me in the past, I've changed them multiple times before settling on what they are now, especially the blue. I've also tried to match their saturation level to some degree against the other dark variants but I was never able to get it perfect.

I'll see about changing the orange tho, shouldn't be that difficult compared to the 16 color palette.

I did try my hand at tweaking the colors a smidge bit and here's what I came up with:
![colors](https://user-images.githubusercontent.com/4509009/58370313-40c92980-7f05-11e9-8696-0fc0014de71e.png)

**Comment by McSinyx** [comment]
Thank you for changing orange, and I think I absolutely love the new green and blue. But I have to agree with you that *colors are really subjective*, and may even varies from one display to another (I bet most programmers don't bother calibrating their monitors), so changes must be carefully decided. It's certainly easier for orange since we want it to be 256-col compatible and there aren't a lot to choose from, but in this 24-bit case...

Slightly related to this, what do you guys think about modularize color choice? To quote the README:

> [we] loved the syntax color choices of Gruvbox

I think many would agree, and a 16-color scheme w/o bullshit (quoting @romainl) which users may choose which terminal color to substitude in would be lovely. I imagine it to be configurable using global variables, i.e.

```vim
let g:srcery_green = '#45ab44'
let g:srcery_blue  = '#0879e3'
```

We'd also need to give grays more sensible names such as `{b,f}g{1,2,3,4}`.

**Comment by roosta** [comment]
That's a good idea, I did that for the [emacs theme](https://github.com/srcery-colors/srcery-emacs), enabled all the GUI hexes to be customizable (if that is what you mean?). I'm not sure I understand what you mean by the gray colors?

**Comment by McSinyx** [comment]
> That's a good idea, I did that for the emacs theme, enabled all the GUI hexes to be customizable (if that is what you mean?).

Yes, definitely. What we get is quite similar to base16, but eh, I don't like base16 highlighting choices very much.

Currently srcery uses 5 extra grays from xterm 256 colors, namely `xgray{1,2,3,4,5}`. For a different settings of color, esp. `white` and `black`, these intermediate colors might need tweaking too, and what I suggested a more friendly name for theme, based on what Gruvebox uses.

**Comment by roosta** [comment]
I agree the gray color names could be more descriptive, but as far the rest goes it was a conscious choice to keep the names as simple as possible. I was never a fan of calling them anything but what they are color wise and I've designed both srcery vim and emacs to not use color aliases of any kind. I think themes are easier to develop that way, especially when adding new hi groups/faces.  There is also no guarantee that say bg1 would actually consistently be used as a background color. The grays are used all over the place, for a number of things.

The grays could be named something like
```vim
let g:srcery_gray_235
```
Your suggestion of making the colors customizable is a good one. I'll put together a pull request when I have the time.

**Comment by McSinyx** [comment]
Since the original issue is solved, I think I'll close this thread for now.
