### ISSUE TITLE
Mismatching background color on embedded vim terminal

### ISSUE THREAD

**Issue by ElArtista** [srcery-colors/srcery-vim#67]
If you open a terminal inside vim using for example `:vert term` or `:tab term` you will see that the background colors mismatch:

![image](https://user-images.githubusercontent.com/4622346/126591134-cd09ac32-25a6-4f76-890b-49ec6facefeb.png)

This does not happen with themes such as tokyonight.

**Comment by roosta** [comment]
Hi, and thanks for opening an issue! This is intentional, we set the terminal background color to `hard_black`. We can set it to normal background color if you find it jarring. Seems neovim doesn't have the hard black color so it would be good for consistency I think. Any thoughts @MindTooth?

**Comment by MindTooth** [comment]
I’ve noticed the same about Neo vs. Vim that they have a different color for the terminal.

Personally, I like more the darker color in Vim.  Because then I know this is a terminal.  Took me a time before I figured out that the window in Neo was infact a terminal. 😅  Just my two cents.  But, I fully understand that having a black window is a bit out of place.

**Comment by roosta** [comment]
That's a good point, its a good way to spot the difference. An alternative is setting neovim terminal to hard_black as well :smile:

**Comment by ElArtista** [comment]
Can we make this configurable? Many times you want a bottom split and the background mismatch does not look nice...

**Comment by roosta** [comment]
Sure, I can add a config opt, hang on a minute

**Comment by roosta** [comment]
Now there's a config option:
```vim
let g:srcery_hard_black_terminal_bg=0
```
default is enabled

**Comment by ElArtista** [comment]
Just tested it and it works. Thank you very much! Closing...
